145_晁捷_第四次作业
Guigulive/Team-O pull request #42
Opened 2018-03-25 14:55 UTC by chaojie1022

2018-03-27 03:22 UTC, brightq commented on Lesson-4/assignment/payroll/test/payroll-testAddEmployee.js
> +    }).then(() =>{
我没这么写过，确定上面出错后下面的then还可以运行是吗？如果要检查错也 catch(function(error) 可能更方便。

2018-03-27 03:23 UTC, brightq requested changes
1. 没有看到migrations 文件夹里的deploy文件，请添加。
2， 因为没有把整个project交进来所以我不能做测试，你确定在你的环境里都能跑通吗。 最好做一个截图。

2018-03-29 22:33 UTC, chaojie1022 commented on Lesson-4/assignment/payroll/test/payroll-testAddEmployee.js
> +    }).then(() =>{
可以这么写，不过写法已经改过来了

2018-03-29 22:34 UTC, chaojie1022 commented
增加了migrations文件 与截图 ，修改了原先部分写法

2018-03-30 19:43 UTC, closed without merging