145_晁捷_第一课作业
Guigulive/Team-O pull request #7
Opened 2018-03-13 20:56 UTC by chaojie1022

@minzhi3 @Smillence @h1994st @ruoshuigao @slofslb

2018-03-13 20:57 UTC, chaojie1022 commented
第一课作业

2018-03-14 15:55 UTC, brightq requested changes
需要把下面两点改一下

2018-03-14 15:55 UTC, brightq commented on Lesson-1/assignment/payroll.sol
> +        salary = s * 1 ether;
这里的逻辑有问题，如果先把新工资赋值了那么发旧工资时就无法用旧工资发了。

2018-03-14 15:55 UTC, brightq commented on Lesson-1/assignment/payroll.sol
> +    function updateAddress(address e){
updateAddress 和 updateSalary 应该需要把旧工资去掉。像updateEmployee 一样

2018-03-16 21:20 UTC, chaojie1022 commented
错误代码已经更新，请批改，谢谢。

2018-03-17 05:59 UTC, brightq approved these changes
GoodWork！ Approved

2018-03-17 06:00 UTC, merged