142_张嘉_第一课作业
Guigulive/Team-O pull request #9
Opened 2018-03-14 15:04 UTC by mind-gravity

我是插班生，今天下午才入学，所以这次作业晚了点交，请谅解。

2018-03-14 15:51 UTC, brightq requested changes
作业中需要增加updateEmployeeAddress 和UpdateSalary的两个功能 可以参考一下origin的文件然后基于那个做改动。

2018-03-14 16:50 UTC, mind-gravity commented
为了验证自己的学习成果，特意不看参考答案。

从解决问题的角度来说，参考答案是用了2步实现可变地址和可变薪水。第一步用updateEmployee函数获取参数address e, uint s，再将参数已赋值的变量给getPaid函数进行支付。那么我秉着节约gas的精神，直接让getpaid函数去获取参数不就好了么，何必分2步走呢？从客户端体验角度来说，都是填入2个参数，点一下鼠标，完成领薪水。流程上是一模一样，结果上也是一模一样。唯一的不同，我的code更节约gas。

另外从产品逻辑角度来说，课件中老董老师实现的功能是只有合约主frank才有权给自己的地址领薪水，其他地址不行。那我也是按照这个思路执行的。

希望能理解。

2018-03-15 09:02 UTC, brightq commented on Lesson-1/assignment/yours.sol
> +        if (msg.sender != owner) {
除了comments，似乎只是改动了 assert 和 require 变成了用If

2018-03-15 09:06 UTC, brightq approved these changes
其实可以把updateEmployee分开来写，或者完善下其它的功能，比如如果pay之前check以下balance之类。Approved

2018-03-15 09:07 UTC, merged

2018-03-15 11:26 UTC, mind-gravity commented on Lesson-1/assignment/yours.sol
> +        if (msg.sender != owner) {
想要看原创的东西可以看之前几次被reject的commit。尤其是前一次commit，跟答案完全不一样的产品逻辑。我想自己用所学实现一些新功能新业务逻辑却被告知跟参考答案不符，我照抄答案又被吐槽……所以我有点迷茫到底是要考察学生什么。我可能还是太初级了。